#ifndef SETTINGS_H_
#define SETTINGS_H_

#include <avr/io.h>

#define F_CPU 16000000
#define STK_BAUD_RATE 57600


#define PIC_PIN_DATA PORTB0


#define PIC_PIN_DATA_PORT PORTB
#define PIC_PIN_DATA_DDR DDRB
#define PIC_PIN_DATA_BIT PORTB0

#define PIC_PIN_CLK_PORT PORTB
#define PIC_PIN_CLK_DDR DDRB
#define PIC_PIN_CLK_PORT_BIT PORTB1

#define PIC_PIN_MCLR_PORT PORTB
#define PIC_PIN_MCLR_DDR DDRB
#define PIC_PIN_MCLR_PORT_BIT PORTB2

#define PIC_PIN_POWER_PORT PORTB
#define PIC_PIN_POWER_DDR DDRB
#define PIC_PIN_POWER_PORT_BIT PORTB3



#define PIC_SIGNATURE_HIGH 0x1e
#define PIC_SIGNATURE_MIDDLE 0x93
#define PIC_SIGNATURE_LOW 0x07




#define AVR_PIN_RESET_PORT PORTB
#define AVR_PIN_RESET_DDR DDRB
#define AVR_PIN_RESET_BIT PORTB4

#define AVR_PIN_SCK_PORT PORTB
#define AVR_PIN_SCK_DDR DDRB
#define AVR_PIN_SCK_BIT PORTB5

#define AVR_PIN_MISO_PORT PORTB
#define AVR_PIN_MISO_DDR DDRB
#define AVR_PIN_MISO_BIT PORTB5

#define AVR_PIN_MOSI_PORT PORTB
#define AVR_PIN_MOSI_DDR DDRB
#define AVR_PIN_MOSI_BIT PORTB5

#define STK_PIN_LED_PORT PORTB
#define STK_PIN_LED_DDR DDRB
#define STK_PIN_LED_BIT PORTB6


#endif